<template>
    <div>
        <table border="1">
            <tr>
                <td><input v-model="users[0].name.first"/></td>
                <td><input v-model="users[0].name.last"/></td>
                <td><input v-model="users[0].company"/></td>
                <td><input v-model="users[0].email"/></td>
                <td><input v-model="users[0].phone"/></td>
                <td><input v-model="users[0].age"/></td>
                <td><input v-model="users[0].balance"/></td>
            </tr>
        </table>

        <pre>{{ users[0] }}</pre>

    </div>
</template>

<script>
export default {
  data() {
    return {
      users: [
        {
          _id: '5b5d6c9ffb2bcfc56afa1d50',
          index: 0,
          guid: '824753e3-9d34-4548-be38-6936bc33083a',
          isActive: true,
          balance: '$3,563.87',
          age: 27,
          eyeColor: 'blue',
          name: {
            first: 'Stefanie',
            last: 'Garza',
          },
          company: 'KYAGORO',
          email: 'stefanie.garza@kyagoro.com',
          phone: '+1 (977) 493-2544',
          address: '319 Bills Place, Harviell, Georgia, 1535',
          about: 'Laboris aliqua deserunt sunt incididunt irure nostrud est sint eu velit ex et eiusmod magna. Aliquip fugiat adipisicing laborum aliquip Lorem incididunt reprehenderit laboris veniam. Aute culpa dolore qui voluptate deserunt consectetur reprehenderit reprehenderit aute ipsum officia ex veniam eiusmod. Non consectetur excepteur et Lorem nulla aliqua cillum nulla dolore sunt officia. Ad veniam culpa laboris velit mollit nisi ad esse culpa laboris et ullamco est. Lorem laborum deserunt aliquip eu.',
          registered: 'Tuesday, September 16, 2014 3:13 PM',
          latitude: '76.376617',
          longitude: '134.308721',
          tags: [
            'cillum',
            'adipisicing',
            'adipisicing',
            'sit',
            'pariatur',
          ],
          range: [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
          ],
          friends: [
            {
              id: 0,
              name: 'Reilly Hendrix',
            },
            {
              id: 1,
              name: 'Nixon Santiago',
            },
            {
              id: 2,
              name: 'White Norris',
            },
          ],
          greeting: 'Hello, Stefanie! You have 9 unread messages.',
          favoriteFruit: 'banana',
        },
        {
          _id: '5b5d6c9f898014a36255dcf9',
          index: 1,
          guid: '1825974b-591c-4dce-bf83-36abd1f90e5b',
          isActive: false,
          balance: '$1,740.85',
          picture: 'http://placehold.it/32x32',
          age: 40,
          eyeColor: 'green',
          name: {
            first: 'Smith',
            last: 'Silva',
          },
          company: 'MAXIMIND',
          email: 'smith.silva@maximind.ca',
          phone: '+1 (907) 598-3569',
          address: '684 Monroe Street, Grenelefe, Kansas, 2419',
          about: 'Excepteur ea nostrud deserunt in anim nisi culpa exercitation dolore consequat. Velit Lorem incididunt excepteur fugiat dolore consectetur proident. Eu nulla veniam adipisicing ea occaecat ad voluptate. Veniam exercitation aliqua reprehenderit exercitation mollit duis dolore exercitation fugiat labore commodo deserunt eu.',
          registered: 'Tuesday, August 29, 2017 5:42 AM',
          latitude: '-21.18969',
          longitude: '63.416267',
          tags: [
            'labore',
            'veniam',
            'magna',
            'fugiat',
            'tempor',
          ],
          range: [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
          ],
          friends: [
            {
              id: 0,
              name: 'Lynette Albert',
            },
            {
              id: 1,
              name: 'Bettye Workman',
            },
            {
              id: 2,
              name: 'Fern Savage',
            },
          ],
          greeting: 'Hello, Smith! You have 5 unread messages.',
          favoriteFruit: 'apple',
        },
        {
          _id: '5b5d6c9fc6423f3918764beb',
          index: 2,
          guid: '9f366766-a349-4851-843f-7c028bb83530',
          isActive: true,
          balance: '$2,759.92',
          picture: 'http://placehold.it/32x32',
          age: 31,
          eyeColor: 'blue',
          name: {
            first: 'Phoebe',
            last: 'Gilbert',
          },
          company: 'CONFERIA',
          email: 'phoebe.gilbert@conferia.info',
          phone: '+1 (949) 519-2457',
          address: '263 Christopher Avenue, Dale, South Dakota, 189',
          about: 'Est nisi pariatur culpa commodo enim sint quis. Mollit ut cillum proident anim exercitation sunt proident proident velit dolor. Sint consequat labore voluptate aute laboris elit nostrud ut esse adipisicing.',
          registered: 'Sunday, October 23, 2016 1:05 PM',
          latitude: '-16.214181',
          longitude: '-59.876148',
          tags: [
            'duis',
            'reprehenderit',
            'nostrud',
            'dolore',
            'non',
          ],
          range: [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
          ],
          friends: [
            {
              id: 0,
              name: 'Farrell Beck',
            },
            {
              id: 1,
              name: 'Janette Roberts',
            },
            {
              id: 2,
              name: 'Logan Warner',
            },
          ],
          greeting: 'Hello, Phoebe! You have 9 unread messages.',
          favoriteFruit: 'banana',
        },
        {
          _id: '5b5d6c9f6147fc47a9bf8046',
          index: 3,
          guid: '302efc6c-5397-4ee2-9b81-74d358a5609d',
          isActive: false,
          balance: '$2,109.11',
          picture: 'http://placehold.it/32x32',
          age: 34,
          eyeColor: 'brown',
          name: {
            first: 'Deloris',
            last: 'Mullen',
          },
          company: 'EARTHWAX',
          email: 'deloris.mullen@earthwax.me',
          phone: '+1 (936) 517-3769',
          address: '256 Narrows Avenue, Hayden, Nevada, 7895',
          about: 'Labore velit non fugiat sit quis magna aute dolor consequat esse elit anim deserunt fugiat. Est magna cupidatat irure duis et duis tempor ad reprehenderit sit commodo. Nostrud exercitation amet nostrud aliquip laboris fugiat. Veniam culpa est consequat laborum occaecat duis tempor. Aliquip velit id commodo sit. Ut ea Lorem sunt labore amet ullamco duis commodo. Elit adipisicing elit ullamco quis incididunt occaecat consequat ullamco et consectetur esse deserunt minim.',
          registered: 'Saturday, July 16, 2016 2:14 PM',
          latitude: '-88.298223',
          longitude: '64.572048',
          tags: [
            'fugiat',
            'quis',
            'in',
            'nostrud',
            'ullamco',
          ],
          range: [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
          ],
          friends: [
            {
              id: 0,
              name: 'Mcleod Holder',
            },
            {
              id: 1,
              name: 'Cecelia Meadows',
            },
            {
              id: 2,
              name: 'Annette Stokes',
            },
          ],
          greeting: 'Hello, Deloris! You have 6 unread messages.',
          favoriteFruit: 'apple',
        },
        {
          _id: '5b5d6c9ffe8953c32a875730',
          index: 4,
          guid: 'e23c602c-4b70-4f0a-a3af-4ee3ab1fc855',
          isActive: false,
          balance: '$3,139.86',
          picture: 'http://placehold.it/32x32',
          age: 26,
          eyeColor: 'brown',
          name: {
            first: 'Cooke',
            last: 'Miranda',
          },
          company: 'IMAGINART',
          email: 'cooke.miranda@imaginart.org',
          phone: '+1 (838) 559-2767',
          address: '898 Classon Avenue, Newkirk, Washington, 1923',
          about: 'Esse sit eu ex consequat Lorem id ad. Excepteur do ut commodo quis amet nostrud labore sint est nostrud do culpa eu id. Voluptate qui aliquip nulla in adipisicing fugiat qui aliqua cupidatat ex. Pariatur laboris elit consectetur velit. Est amet ullamco id pariatur aliquip id ad ea elit nisi aute commodo ipsum. Nisi commodo nostrud veniam laboris.',
          registered: 'Thursday, August 27, 2015 5:36 PM',
          latitude: '-48.550654',
          longitude: '-133.459501',
          tags: [
            'nostrud',
            'labore',
            'sunt',
            'veniam',
            'ipsum',
          ],
          range: [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
          ],
          friends: [
            {
              id: 0,
              name: 'Jessica Lowe',
            },
            {
              id: 1,
              name: 'Roach Robinson',
            },
            {
              id: 2,
              name: 'Annabelle Morales',
            },
          ],
          greeting: 'Hello, Cooke! You have 7 unread messages.',
          favoriteFruit: 'banana',
        },
        {
          _id: '5b5d6c9fd9a5c095f905e30a',
          index: 5,
          guid: '260918d5-f6e1-4c11-9b20-0f41a7f9d766',
          isActive: false,
          balance: '$1,037.59',
          picture: 'http://placehold.it/32x32',
          age: 27,
          eyeColor: 'green',
          name: {
            first: 'Elba',
            last: 'Witt',
          },
          company: 'ENTHAZE',
          email: 'elba.witt@enthaze.tv',
          phone: '+1 (914) 401-2836',
          address: '233 Cadman Plaza, Motley, Vermont, 5697',
          about: 'In amet esse sit exercitation nisi esse culpa ullamco tempor proident id. Nulla nulla eu et consequat pariatur exercitation culpa dolor sit fugiat magna. Aliquip pariatur dolore magna ullamco dolor elit. Irure aliqua culpa irure fugiat minim sint adipisicing sunt pariatur reprehenderit duis est labore. Magna culpa qui cupidatat occaecat consectetur sunt fugiat proident quis nulla do aliqua reprehenderit fugiat.',
          registered: 'Sunday, September 7, 2014 9:36 AM',
          latitude: '20.32035',
          longitude: '-31.202977',
          tags: [
            'pariatur',
            'excepteur',
            'adipisicing',
            'non',
            'labore',
          ],
          range: [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
          ],
          friends: [
            {
              id: 0,
              name: 'Kristi Dawson',
            },
            {
              id: 1,
              name: 'Hogan Morgan',
            },
            {
              id: 2,
              name: 'Lidia Moran',
            },
          ],
          greeting: 'Hello, Elba! You have 5 unread messages.',
          favoriteFruit: 'apple',
        },
        {
          _id: '5b5d6c9fe98859bf8b4375ec',
          index: 6,
          guid: 'cac9973c-5f19-40af-bbd9-9f266322e5e2',
          isActive: false,
          balance: '$1,288.22',
          picture: 'http://placehold.it/32x32',
          age: 32,
          eyeColor: 'blue',
          name: {
            first: 'Gilbert',
            last: 'Church',
          },
          company: 'INTRAWEAR',
          email: 'gilbert.church@intrawear.us',
          phone: '+1 (801) 568-2169',
          address: '159 Aberdeen Street, Nettie, Rhode Island, 5050',
          about: 'Irure nisi duis proident velit id elit occaecat. Exercitation non veniam quis aliquip tempor magna tempor duis duis et est commodo duis. Cillum ut ullamco eiusmod nostrud ipsum laborum ut ipsum. Labore ad ut veniam sit excepteur. Incididunt in pariatur enim dolor nulla duis.',
          registered: 'Sunday, March 5, 2017 4:29 AM',
          latitude: '48.262518',
          longitude: '-157.782471',
          tags: [
            'quis',
            'incididunt',
            'amet',
            'laboris',
            'id',
          ],
          range: [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
          ],
          friends: [
            {
              id: 0,
              name: 'Juana Pollard',
            },
            {
              id: 1,
              name: 'Dyer Patrick',
            },
            {
              id: 2,
              name: 'Dodson Ryan',
            },
          ],
          greeting: 'Hello, Gilbert! You have 8 unread messages.',
          favoriteFruit: 'banana',
        },
      ],
    };
  },
};
</script>
